enum ClassType {
  deal = 'deal',
  rise = 'rise',
  down = 'down',
  wave = 'wave',
  none = '',
  cement = '水泥工業',
  food = '食品工業',
  plastic ='塑膠工業',
  build =​'建材營造業',
  car ='汽車工業',
  other ='其他業',
  textile ='紡織纖維',
  department ='貿易百貨業',
electronicParts ='電子零組件業',
mechanical ='電機機械',
biologocal ='生技醫療業',
​device ='電器電纜',
chemistry = '化學工業',
glass ='玻璃陶瓷',
paper ='造紙工業',
steel ='鋼鐵工業',
​rubber ='橡膠工業',
shipping ='航運業',
computer ='電腦及週邊設備業',
semiconductor ='半導體業',
otherElectronic ='其他電子業',
internet ='通信網路業',
photoelectric ='光電業',
electronicPath ='電子通路業',​information ='資訊服務業',
energy ='油電燃氣業',
sightseeing ='觀光事業',
finance ='金融保險業'
}

export default ClassType;
